/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amrish' at '4/20/16 1:13 PM' with Gradle 2.12
 *
 * @author amrish, @date 4/20/16 1:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
